## library() calls go here
library(conflicted)
library(dotenv)
library(drake)
library(R.utils)
# data management
library(haven)
library(janitor)
library(magrittr)
# data analysis
library(foreach)
library(tidyverse)
library(tidymodels)
library(embed)
library(tidyposterior)
library(ranger)
library(survival)
library(rms)
library(obliqueRSF)
library(xgboost)
library(xgboost.surv)
library(riskRegression)
library(naniar)
library(MASS)
library(Hmisc)
library(rstanarm)
# reporting
library(table.glue)
library(tibbleOne)
library(officer)
library(glue)
library(flextable)
library(devEMF)
library(diagram)
library(magick)
library(paletteer)
library(ggdist)
library(ggsci)

conflicted::conflict_prefer("roc",       "pROC")
conflicted::conflict_prefer("filter",    "dplyr")
conflicted::conflict_prefer("slice",     "dplyr")
conflicted::conflict_prefer("select",    "dplyr")
conflicted::conflict_prefer("summarise", "dplyr")
conflicted::conflict_prefer("summarize", "dplyr")
conflicted::conflict_prefer("gather",    "tidyr")
conflicted::conflict_prefer("set_names", "purrr")
conflicted::conflict_prefer("plan",      "drake")

